### ISSUE TITLE
Split status mail flag with success and failure

### ISSUE THREAD

**Issue by ghost** [igbt6/Packt-Publishing-Free-Learning#50]
Actually the script is very spamer sending all the correct fetched books, when I only want to see if an error happened, like before with -rm

Can you recover this funcionality? for example, with 2 flags one OK, other for Failure (and the actual that enables both)

**Comment by igbt6** [comment]
Hello, Yes we changed the behaviuor a bit, the feature was implemented at: https://github.com/igbt6/Packt-Publishing-Free-Learning/issues/42 by @mjenczmyk . Maybe it's worth to make this notifications seperate. As I am overloaded currently, do you maybe want to open a pull request :) ?

**Comment by mjenczmyk** [comment]
@Palatosino I implemented it that way, because I wanted to make sure I know something failed - if a service I set a cron on failed I wouldn't get an email at all (and I would be convinced everything went OK, because I didn't get an email.

Anyway, I'm not sure if it still matters as there is capcha to be solved before grabbing - if I were you I would wait to see if they have removed captcha (the script is still an awesome tool for downloading already claimed books thought).

**Comment by mjenczmyk** [comment]
@Palatosino Can this issue be closed as it seems that grabbing books with scheduled task is impossible because of captcha?

**Comment by igbt6** [comment]
Close for now, I will try to recover the previous functionality in future as it was more useful for me as well
